services:
  server:
    build:
      context: ./server
      dockerfile: ./Dockerfile
    ports:
      - "3333:3333"
    environment:
      - PORT=3333
      - MONGO_URI=mongodb://mongo:27017/tac-med
      - ORIGIN_URL=http://localhost
      - AUTH0_DOMAIN=${AUTH0_DOMAIN}
      - AUTH0_AUDIENCE=${AUTH0_AUDIENCE}
      - SENTRY_DSN=${SENTRY_DSN}
    depends_on:
      - mongo
    networks:
      - tac-med-network

  client:
    build:
      context: ./client
      dockerfile: ./Dockerfile
    ports:
      - "8080:80"
    environment:
      - VITE_API_URL=http://localhost:3333
    depends_on:
      - server
    networks:
      - tac-med-network

  mongo:
    image: mongo:7
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - tac-med-network

networks:
  tac-med-network:
    driver: bridge

volumes:
  mongo-data: