---
- name: Deploy tac-med client
  hosts: all
  become: yes
  
  tasks:
    - name: Create client directory
      file:
        path: "{{ app_dir }}/apps/client"
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0755'
    
    - name: Copy client files
      synchronize:
        src: "{{ playbook_dir }}/../../apps/client/"
        dest: "{{ app_dir }}/apps/client/"
        delete: yes
        rsync_opts:
          - "--exclude=node_modules"
          - "--exclude=dist"
          - "--exclude=.env"
      become_user: "{{ ansible_user }}"
    
    - name: Create client environment file
      template:
        src: ../templates/client.env.j2
        dest: "{{ app_dir }}/apps/client/.env"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0600'
    
    - name: Build client
      shell: |
        cd {{ app_dir }}
        npm run build:client
      become_user: "{{ ansible_user }}"
      environment:
        NODE_ENV: "{{ node_env }}"
        VITE_API_URL: "http://{{ ansible_host }}:{{ server_port }}"
    
    - name: Start client with PM2
      shell: |
        cd {{ app_dir }}
        pm2 delete tac-med-client || true
        pm2 start ecosystem.config.js --only tac-med-client
        pm2 save
      become_user: "{{ ansible_user }}"
      environment:
        PM2_HOME: "/home/{{ ansible_user }}/.pm2"
    
    - name: Wait for client to be ready
      wait_for:
        port: "{{ client_port }}"
        host: 127.0.0.1
        delay: 5
        timeout: 30
    
    - name: Check client is accessible
      uri:
        url: "http://127.0.0.1:{{ client_port }}"
        method: GET
        status_code: 200
      register: client_check
      retries: 3
      delay: 5