---
- name: Deploy MongoDB for tac-med
  hosts: all
  become: yes

  tasks:
    - name: Ensure MongoDB is installed
      apt:
        name: mongodb-org
        state: present
        update_cache: yes

    - name: Create MongoDB data directory
      file:
        path: /var/lib/mongodb
        state: directory
        owner: mongodb
        group: mongodb
        mode: '0755'

    - name: Create MongoDB log directory
      file:
        path: /var/log/mongodb
        state: directory
        owner: mongodb
        group: mongodb
        mode: '0755'

    - name: Configure MongoDB
      template:
        src: ../templates/mongod.conf.j2
        dest: /etc/mongod.conf
        backup: yes
      notify: restart mongodb

    - name: Start and enable MongoDB service
      systemd:
        name: mongod
        state: started
        enabled: yes
        daemon_reload: yes

    - name: Wait for MongoDB to be ready
      wait_for:
        port: "{{ mongodb_port }}"
        host: 127.0.0.1
        delay: 5
        timeout: 30

    - name: Create tac-med database
      shell: |
        mongosh --eval "
          if (!db.getMongo().getDBNames().includes('{{ mongodb_database }}')) {
            db.getSiblingDB('{{ mongodb_database }}').createCollection('init');
            print('Database {{ mongodb_database }} created');
          } else {
            print('Database {{ mongodb_database }} already exists');
          }
        "
      register: db_creation
      changed_when: "'created' in db_creation.stdout"

  handlers:
    - name: restart mongodb
      systemd:
        name: mongod
        state: restarted