---
# Ansible Galaxy requirements for Tac-Med deployment

collections:
  - name: community.general
    version: ">=6.0.0"
  - name: community.mongodb
    version: ">=1.4.0"
  - name: ansible.posix
    version: ">=1.4.0"

roles:
  - name: geerlingguy.nodejs
    version: "7.0.0"
  - name: geerlingguy.mongodb
    version: "3.2.0"
  - name: geerlingguy.nginx
    version: "3.1.4"
  - name: geerlingguy.firewall
    version: "2.7.1"